<tr><td><a href='https://github.com/badmojr/1Hosts' target='_blank'>1Hosts</a></td><td>badmojr</td><td>69,620</td><td><a href='filter/1hosts.cf.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/badmojr/1Hosts' target='_blank'>1Hosts Pro</a></td><td>badmojr</td><td>214,129</td><td><a href='filter/1hosts.cf-pro.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://280blocker.net/' target='_blank'>280blocker</a></td><td>280blocker</td><td></td><td><a href='filter/280blocker.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/ABPindo/indonesianadblockrules/' target='_blank'>ABPindo</a></td><td>ABPindo</td><td>306</td><td><a href='filter/abpindo.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://adaway.org/' target='_blank'>ADAway</a></td><td>ADAway</td><td>7,355</td><td><a href='filter/adaway.org.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/jdlingyu/ad-wars' target='_blank'>ad-wars</a></td><td>jdlingyu</td><td>1,614</td><td><a href='filter/ad-wars.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://gurud.ee' target='_blank'>Adblock Filters by Gurud.ee</a></td><td>Gurud OÜ</td><td>33</td><td><a href='filter/adblock-estonian.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/realodix/AdBlockID' target='_blank'>Adblock Filters by Gurud.ee</a></td><td>realodix</td><td>97</td><td><a href='filter/adblock-id.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/farrokhi/adblock-iran' target='_blank'>Adblock-Iran</a></td><td>farrokhi</td><td>77</td><td><a href='filter/adblock-iran.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdroitAdorKhan/EnergizedProtection' target='_blank'>Ador's Energized Pro List</a></td><td>Ador</td><td>11,148</td><td><a href='filter/ador-energized.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdroitAdorKhan/EnergizedProtection' target='_blank'>Ador's Energized Pro Porn List</a></td><td>Ador</td><td></td><td><a href='filter/ador-energized-porn.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdguardSDNSFilter' target='_blank'>AdGuard DNS filter</a></td><td>AdguardTeam</td><td>47,721</td><td><a href='filter/adguard-dns.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Dutch filter</a></td><td>AdguardTeam</td><td>50</td><td><a href='filter/adguard-dutch-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Base filter (English)</a></td><td>AdguardTeam</td><td>27,912</td><td><a href='filter/adguard-english-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard French filter</a></td><td>AdguardTeam</td><td>11,131</td><td><a href='filter/adguard-french-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard German filter</a></td><td>AdguardTeam</td><td>494</td><td><a href='filter/adguard-german-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Japanese filter</a></td><td>AdguardTeam</td><td>373</td><td><a href='filter/adguard-japanese-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Mobile Adservers</a></td><td>AdguardTeam</td><td>1,050</td><td><a href='filter/adguard-mobile-ads.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Mobile Ads filter</a></td><td>AdguardTeam</td><td>1,088</td><td><a href='filter/adguard-mobile-ads-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Mobile Specific</a></td><td>AdguardTeam</td><td>78</td><td><a href='filter/adguard-mobile-specific.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Russian filter</a></td><td>AdguardTeam</td><td>4,062</td><td><a href='filter/adguard-russian-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Suffari filter</a></td><td>AdguardTeam</td><td></td><td><a href='filter/adguard-safari.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Social Media filter</a></td><td>AdguardTeam</td><td>61</td><td><a href='filter/adguard-social-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Social Trackers</a></td><td>AdguardTeam</td><td>53</td><td><a href='filter/adguard-social-trackers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Spanish/Portuguese filter</a></td><td>AdguardTeam</td><td>239</td><td><a href='filter/adguard-spanish-portuguese-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Tracking Protection filter</a></td><td>AdguardTeam</td><td>29,133</td><td><a href='filter/adguard-tracking-protection.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Tracking Firstparty</a></td><td>AdguardTeam</td><td>2,193</td><td><a href='filter/adguard-tracking-firstparty.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Tracking Servers</a></td><td>AdguardTeam</td><td>4,787</td><td><a href='filter/adguard-tracking-servers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/AdGuardFilters' target='_blank'>AdGuard Turkish filter</a></td><td>AdguardTeam</td><td>369</td><td><a href='filter/adguard-turkish-filter.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/Hubird-au/Adversity/' target='_blank'>Adversity Anti Social</a></td><td>Hubird-au</td><td>39</td><td><a href='filter/adversity-anti-social.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://rlwpx.free.fr/WPFF' target='_blank'>Airelle PUB</a></td><td>Airelle</td><td></td><td><a href='filter/airelle-pub.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://rlwpx.free.fr/WPFF' target='_blank'>Airelle RSK</a></td><td>Airelle</td><td></td><td><a href='filter/airelle-rsk.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://rlwpx.free.fr/WPFF' target='_blank'>Airelle SEX</a></td><td>Airelle</td><td></td><td><a href='filter/airelle-sex.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://rlwpx.free.fr/WPFF' target='_blank'>Airelle TRC</a></td><td>Airelle</td><td></td><td><a href='filter/airelle-trc.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/Yhonay/antipopads/' target='_blank'>antipopads</a></td><td>Yhonay</td><td>755</td><td><a href='filter/antipopads.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/anudeepND/blacklist' target='_blank'>Anudeep's Blacklist</a></td><td>Anudeep</td><td>42,361</td><td><a href='filter/anudeep-adservers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/paulgb/BarbBlock' target='_blank'>BarbBlock</a></td><td>paulgb</td><td>542</td><td><a href='filter/barbblock.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://better.fyi/trackers/' target='_blank'>Better.fyi Trackers</a></td><td>anarki999</td><td>612</td><td><a href='filter/better-fyi-trackers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/bjornstar/hosts' target='_blank'>bjornstar hosts</a></td><td>bjornstar</td><td>6,237</td><td><a href='filter/bjornstar-hosts.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/stamparm/blackbook/' target='_blank'>blackbook</a></td><td>stamparm</td><td>17,825</td><td><a href='filter/blackbook.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/Clefspeare13/pornhosts' target='_blank'>pornhosts</a></td><td>Clefspeare13</td><td></td><td><a href='filter/clefspeare-pornhosts.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://cybercrime-tracker.net/' target='_blank'>cybercrime</a></td><td>-</td><td></td><td><a href='filter/cybercrime.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/DandelionSprout/adfilt' target='_blank'>Dandelion Sprouts nordiske filtre</a></td><td>DandelionSprout</td><td>374</td><td><a href='filter/dandelion-sprouts-nordic-filters.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://osint.digitalside.it/' target='_blank'>DigitalSide Threat-Intel</a></td><td>DigitalSide</td><td>62</td><td><a href='filter/digitalside-threat-intel.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://disconnect.me/' target='_blank'>disconnect.me Simple Ad</a></td><td>disconnect.me</td><td>2,700</td><td><a href='filter/disconnect.me-ad.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://disconnect.me/' target='_blank'>disconnect.me Malvertising</a></td><td>disconnect.me</td><td>2,734</td><td><a href='filter/disconnect.me-malvertising.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://disconnect.me/' target='_blank'>disconnect.me Tracking</a></td><td>disconnect.me</td><td>34</td><td><a href='filter/disconnect.me-tracking.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList</a></td><td>EasyList</td><td>23,057</td><td><a href='filter/easylist.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Adservers</a></td><td>EasyList</td><td>20,756</td><td><a href='filter/easylist-adservers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Adult Adservers</a></td><td>EasyList</td><td>498</td><td><a href='filter/easylist-adult-adservers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Adult Thirdparty</a></td><td>EasyList</td><td>97</td><td><a href='filter/easylist-adult-thirdparty.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Adult Specific</a></td><td>EasyList</td><td>35</td><td><a href='filter/easylist-adult-specific.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylistbrasil.github.io/' target='_blank'>EasyList Brasil</a></td><td>EasyList</td><td>392</td><td><a href='filter/easylist-brasil.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://abpchina.org/forum/' target='_blank'>Easylist Czech and Slovak filter</a></td><td>EasyList</td><td>8,726</td><td><a href='filter/easylist-china.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/tomasko126/easylistczechandslovak' target='_blank'>EasyList China</a></td><td>adblock.sk</td><td>95</td><td><a href='filter/easylist-czech-and-slovak.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Dutch</a></td><td>EasyList</td><td>42</td><td><a href='filter/easylist-dutch.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList French</a></td><td>EasyList</td><td>11,108</td><td><a href='filter/easylist-french.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Germany</a></td><td>EasyList</td><td>432</td><td><a href='filter/easylist-germany.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Italy</a></td><td>EasyList</td><td>264</td><td><a href='filter/easylist-italy.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList India</a></td><td>EasyList</td><td>79</td><td><a href='filter/easylist-india.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Korea</a></td><td>EasyList</td><td>49</td><td><a href='filter/easylist-korea.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Polish</a></td><td>EasyList</td><td>72</td><td><a href='filter/easylist-polish.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Russian</a></td><td>EasyList</td><td>8,874</td><td><a href='filter/easylist-russian.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyList Spanish</a></td><td>EasyList</td><td>389</td><td><a href='filter/easylist-spanish.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist-thailand.github.io/' target='_blank'>EasyList Thailand</a></td><td>EasyList-Thailand</td><td>622</td><td><a href='filter/easylist-thailand.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyPrivacy</a></td><td>EasyList</td><td>19,384</td><td><a href='filter/easyprivacy.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyPrivacy Specific</a></td><td>EasyList</td><td>744</td><td><a href='filter/easyprivacy-specific.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyPrivacy Thirdparty</a></td><td>EasyList</td><td>1,295</td><td><a href='filter/easyprivacy-thirdparty.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>EasyPrivacy Tracking Servers</a></td><td>EasyList</td><td>4,425</td><td><a href='filter/easyprivacy-tracking-servers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/MetaMask/eth-phishing-detect' target='_blank'>eth-phishing-detect</a></td><td>MetaMask</td><td>1,071</td><td><a href='filter/eth-phishing-detect.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/FadeMind/hosts.extras' target='_blank'>FadeMind-add.2o7net</a></td><td>FadeMind</td><td>2,030</td><td><a href='filter/fademind-add.2o7net.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/FadeMind/hosts.extras' target='_blank'>FadeMind-add.dead</a></td><td>FadeMind</td><td>14</td><td><a href='filter/fademind-add.dead.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/FadeMind/hosts.extras' target='_blank'>FadeMind-add.risk</a></td><td>FadeMind</td><td>2,186</td><td><a href='filter/fademind-add.risk.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/FadeMind/hosts.extras' target='_blank'>FadeMind-add.spam</a></td><td>FadeMind</td><td>56</td><td><a href='filter/fademind-add.spam.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://www.fanboy.co.nz/' target='_blank'>Fanboy's Annoyance List</a></td><td>EasyList</td><td>9,984</td><td><a href='filter/fanboy-annoyance.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://www.fanboy.co.nz/' target='_blank'>Fanboy's Complete List</a></td><td>EasyList</td><td>42,488</td><td><a href='filter/fanboy-complete.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='http://www.fanboy.co.nz/' target='_blank'>Fanboy's Enhanced Tracking List</a></td><td>EasyList</td><td>127</td><td><a href='filter/fanboy-enhanced-stats.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://gnuzilla.gnu.org/filters' target='_blank'>gnuzilla</a></td><td>gnuzilla</td><td></td><td><a href='filter/gnuzilla.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://hexxiumcreations.github.io/threat-list/' target='_blank'>Hexxium Creations Threat List</a></td><td>Hexxium Creations</td><td>3,318</td><td><a href='filter/hexxium-creations-threat-list.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://bigdargon.github.io/hostsVN/' target='_blank'>hostsVN</a></td><td>bigdargon</td><td>1,732</td><td><a href='filter/hosts-vn.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/PolishFiltersTeam/KADhosts' target='_blank'>KADhosts</a></td><td>PolishFiltersTeam</td><td>95,347</td><td><a href='filter/kadhosts.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/lightswitch05/hosts/' target='_blank'>lightswitch05 - Ads & Tracking</a></td><td>lightswitch05</td><td>426,075</td><td><a href='filter/lightswitch-ads-tracking.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://easylist.to/' target='_blank'>Liste AR</a></td><td>EasyList</td><td>148</td><td><a href='filter/liste-ar.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/matomo-org/referrer-spam-list' target='_blank'>Referrer Spam List</a></td><td>matomo.org</td><td>2,129</td><td><a href='filter/matomo.org-spammers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/hectorm/hblock' target='_blank'>hBlock</a></td><td>hectorm</td><td>300,673</td><td><a href='filter/molinero-hblock.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/neoFelhz/neohosts' target='_blank'>neohosts</a></td><td>neoFelhz</td><td>2,411</td><td><a href='filter/neohosts.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/notracking/hosts-blocklists' target='_blank'>hosts-blocklists</a></td><td>notracking</td><td>120,863</td><td><a href='filter/hosts-blocklists.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://oisd.nl' target='_blank'>oisd.nl-basic</a></td><td>sjhgvr</td><td>86,949</td><td><a href='filter/oisd.nl-basic.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://oisd.nl' target='_blank'>oisd.nl-full</a></td><td>sjhgvr</td><td>915,976</td><td><a href='filter/oisd.nl-full.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://www.openphish.com/' target='_blank'>OpenPhish</a></td><td>openphish</td><td></td><td><a href='filter/openphish.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://pgl.yoyo.org/adservers/' target='_blank'>pgl.yoyo.org</a></td><td>pgl.yoyo.org</td><td>3,666</td><td><a href='filter/pgl.yoyo.org.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/mhxion/pornaway' target='_blank'>PornAway</a></td><td>mhxion</td><td>30,911</td><td><a href='filter/pornaway.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/chadmayfield/my-pihole-blocklists' target='_blank'>porn-top1million</a></td><td>chadmayfield</td><td>11,812</td><td><a href='filter/porn-top1million.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://dsi.ut-capitole.fr/blacklists/index_en.php' target='_blank'>Prigent Ads</a></td><td>Fabrice Prigent</td><td></td><td><a href='filter/prigent-ads.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://dsi.ut-capitole.fr/blacklists/index_en.php' target='_blank'>Prigent Adult</a></td><td>Fabrice Prigent</td><td></td><td><a href='filter/prigent-adult.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://dsi.ut-capitole.fr/blacklists/index_en.php' target='_blank'>Prigent Cryptojacking</a></td><td>Fabrice Prigent</td><td></td><td><a href='filter/prigent-cryptojacking.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://dsi.ut-capitole.fr/blacklists/index_en.php' target='_blank'>Prigent Gambling</a></td><td>Fabrice Prigent</td><td></td><td><a href='filter/prigent-gambling.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://dsi.ut-capitole.fr/blacklists/index_en.php' target='_blank'>Prigent Phishing</a></td><td>Fabrice Prigent</td><td></td><td><a href='filter/prigent-phishing.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://gitlab.com/quidsup/notrack-blocklists/' target='_blank'>NoTrack Tracker Blocklist</a></td><td>quidsup</td><td>16,472</td><td><a href='filter/quidsup-notrack.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://gitlab.com/quidsup/notrack-blocklists/' target='_blank'>NoTrack Malware Blocklist</a></td><td>quidsup</td><td>961</td><td><a href='filter/quidsup-notrack-malware.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/Sinfonietta/hostfiles' target='_blank'>Sinfonietta - Pornography Hosts</a></td><td>Sinfonietta</td><td>19,389</td><td><a href='filter/sinfonietta-porn.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://someonewhocares.org/hosts' target='_blank'>someonewhocares.org</a></td><td>Dan Pollock</td><td>11,356</td><td><a href='filter/someonewhocares.org.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/StevenBlack/hosts' target='_blank'>Steven Black's Hosts</a></td><td>Steven Black</td><td>173,361</td><td><a href='filter/sbc.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/StevenBlack/hosts' target='_blank'>Steven Black's Hosts - RAW</a></td><td>Steven Black</td><td>2,323</td><td><a href='filter/sbc-hosts.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://stopforumspam.com' target='_blank'>StopForumSpam</a></td><td>StopForumSpam</td><td>42,485</td><td><a href='filter/stopforumspam.com.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/crazy-max/WindowsSpyBlocker' target='_blank'>WindowsSpyBlocker</a></td><td>crazy-max</td><td>347</td><td><a href='filter/windows-spy-blocker.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://winhelp2002.mvps.org/' target='_blank'>MVPS hosts file</a></td><td>mvps.org</td><td>8,725</td><td><a href='filter/winhelp2002.mvps.org.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/yous/YousList' target='_blank'>YousList</a></td><td>yous</td><td>561</td><td><a href='filter/youslist.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
<tr><td><a href='https://github.com/AdguardTeam/cname-trackers' target='_blank'>cname-trackers</a></td><td>AdguardTeam</td><td>50,433</td><td><a href='filter/cname-trackers.txt' title='Filtered Source' target='_blank'>LINK</a></td></tr>
